[package]
name = "pandock-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "multipart", "stream"] }
dav-server = { version = "0.11", default-features = false }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
futures-util = "0.3"
bytes = "1"
md5 = "0.7"
url = "2"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
async-trait = "0.1"
thiserror = "2"
log = "0.4"
semver = "1"
sha2 = "0.10"
hex = "0.4"
zip = { version = "2", default-features = false, features = ["deflate"] }


[dev-dependencies]
wiremock = "0.6"
tempfile = "3"

[features]
dev-updater = []
